name = "d3adpn1"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "c7b44bbe0e40455da9a44655019752a6" }
]
